#!/usr/bin/env python3
"""Import the 13 upstream squads as self-contained ClariFlix skills.

Usage: python scripts/import_free_squads.py --source-root C:/code/maquina-de-receita
Add --check to verify reproducibility without writing, or --output-root for staging.
Only directories generated by this importer can be updated. No squad is executed.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

import yaml

MANAGED_BY = "clariflix-skills/scripts/import_free_squads.py"
VERSION = "0.2.0"
SPECS = {
    "apex-context-supreme": {
        "title": "Contexto sem ruído", "subtitle": "Arquitetura, enriquecimento e otimização de contexto",
        "description": "Organiza o contexto técnico de um projeto em regras para agentes: inventário, blueprint, enriquecimento, redução de redundância e validação por plataforma.",
        "genres": ["Context Engineering", "Agentes de IA"], "traits": ["Estruturada", "Concisa", "Multiplataforma"],
        "requires": "Acesso aos arquivos do projeto e plataformas de destino definidas",
        "example": "Organize o contexto deste projeto para Codex com o Apex Context Supreme",
        "entry": "agents/apex-orquestrista.md", "workflow": "workflows/apex-pipeline.yaml",
        "refs": [("Template de regras", "templates/context-rule.template.md"), ("Gate de qualidade", "checklists/apex-quality-gate.md")],
        "when": "Use para estruturar contexto de um projeto, criar regras de agentes ou reduzir redundância sem perder decisões técnicas. Receba o caminho do projeto e as plataformas de destino.",
        "steps": [
            "Leia o orquestrador Apex e o pipeline. Maven começa por `tasks/arquitetar-apex.md`: inventário real de tecnologias e `blueprint.yaml` antes de qualquer regra.",
            "Spark lê `agents/spark-alquimista.md` e `tasks/enriquecer-apex.md`, derivando regras acionáveis do blueprint com o template de contexto. Gere apenas os destinos pertinentes ao pedido.",
            "Trim aplica `tasks/otimizar-apex.md`: remove repetição preservando requisitos e diferenças entre plataformas. Registre como estimou tokens antes/depois; não apresente estimativa como medição.",
            "Vigil aplica `tasks/validar-apex.md` e o gate: sintaxe, inventário, origem de cada regra e adequação por plataforma. Corrija bloqueadores antes do relatório final."
        ],
        "pitfalls": "Regras sem suporte no blueprint, arquivos de plataformas diferentes idênticos e compressão que elimina restrições são bloqueadores. Não substitua configurações de outras plataformas que o usuário não pediu para alterar.",
        "verify": "Inventário e blueprint válidos; regras rastreáveis e acionáveis; diferenças entre plataformas justificadas; relatório de conformidade sem bloqueadores e métricas com método explícito.",
    },
    "athenaeum-squad": {
        "title": "Sala de estratégia", "subtitle": "Inteligência estratégica e transformação organizacional",
        "description": "Analisa desafios organizacionais por sistemas, cultura, emoções, ética e cenários; produz plano de solução, comunicação e relatório executivo com o Athenaeum.",
        "genres": ["Estratégia", "Organizações"], "traits": ["Sistêmica", "Multidisciplinar", "Analítica"],
        "requires": "Desafio, contexto organizacional, partes interessadas e evidências disponíveis",
        "example": "Use Athenaeum para analisar este desafio organizacional e propor cenários",
        "entry": "agents/chief-strategist.md", "workflow": "workflows/athenaeum-workflow.yaml",
        "refs": [("Intake e contrato de entrada", "tasks/intakeChallenge.md"), ("Síntese final", "tasks/compileFinalReport.md")],
        "when": "Use para decisões complexas de negócio, conflitos entre áreas ou transformação organizacional que demandem múltiplas perspectivas. Delimite a decisão e quem poderá agir sobre o resultado.",
        "steps": [
            "O intake-analyst decodifica o desafio em `tasks/intakeChallenge.md`; avance com `decodedBrief` disponível. O war-room-facilitator organiza stakeholders e contexto em `tasks/facilitateWarRoom.md`.",
            "Siga o pipeline para análise de sistemas, fatores emocionais, cultura e ética. Leia os agentes e tasks dessas perspectivas quando chegar a cada etapa; registre conflitos de evidência e hipóteses em separado.",
            "Creative-ideator gera alternativas; chief-strategist desenvolve cenários; invisible-patterns-analyst procura conexões; chief-strategist desenha a solução. Preserve os contratos Entrada/Saída de cada task.",
            "Communication-specialist cria a estratégia de comunicação em `tasks/craftCommunication.md`. Report-synthesizer recebe esse artefato e consolida decisões, cenários, responsabilidades e próximos passos."
        ],
        "pitfalls": "Os arquivos de agentes são enxutos: não invente dados para preencher perspectivas. Não confunda as checklists de geração/publicação do próprio squad com comprovação de qualidade de uma decisão organizacional.",
        "verify": "Brief decodificado, perspectivas relevantes documentadas, cenários comparados, solução acionável e comunicação coerente com a decisão; cada saída atende o contrato da task seguinte e o relatório distingue fato de hipótese.",
    },
    "brainstormind": {
        "title": "Ideias em duas rodadas", "subtitle": "Divergência, seleção e design com confirmação humana",
        "description": "Conduz brainstorming Diverge+Converge: define temas, gera e filtra ideias em duas rodadas, apresenta Top 3 e desenvolve o insight escolhido em design validado.",
        "genres": ["Criatividade", "Design de Soluções"], "traits": ["Divergente", "Seletiva", "Interativa"],
        "requires": "Tópico, objetivo, profundidade e contexto; participação do usuário nos gates",
        "example": "Use Brainstormind para encontrar ideias para este problema e desenvolver a escolhida",
        "entry": "agents/orchestrator.md", "workflow": "workflows/brain-pipeline.yaml",
        "refs": [("Somente divergência", "workflows/diverge-only.yaml"), ("Setup e modos", "tasks/start.md"), ("Macros", "shared/macros.md"), ("Schemas", "templates/schemas.md")],
        "when": "Use para explorar alternativas e transformar uma escolha em design, ou apenas gerar o Top 3 no modo diverge. Aproveite informações já fornecidas antes de pedir os parâmetros ausentes.",
        "steps": [
            "Leia `tasks/start.md` e o orquestrador para escolher full, diverge ou quick. Registre configuração e contexto; theme-definer define as associações antes da geração.",
            "No modo completo, siga as duas rodadas do pipeline: primeira geração por tema, filtro Top 10, expansão desses candidatos e filtro Top 3. Leia `tasks/generate-ideas.md` e `tasks/filter-and-rank.md` para os critérios e schemas; mantenha os artefatos intermediários rastreáveis.",
            "Synthesizer apresenta Top 3. Preserve o gate interativo: o usuário escolhe o insight antes da facilitação. No modo diverge, entregue aqui conforme o fluxo próprio.",
            "Design-facilitator conduz `tasks/facilitate-design.md`; confirme o Understanding Lock e obtenha aceite do design. Só então report-builder consolida `brain_report.md`. Limpe apenas temporários criados nesta execução, após verificar seu caminho absoluto."
        ],
        "pitfalls": "Não substitua escolha do usuário por voto dos agentes. Nomes de modelos e 24 invocações do original descrevem o runtime de origem: adapte aos recursos disponíveis sem simular concorrência ou afirmar que gerou 200 ideias quando o modo executado produziu menos.",
        "verify": "Temas, critérios e rodadas documentados; Top 3 rastreável às ideias; escolha e Understanding Lock registrados no modo completo; design aceito e relatório final disponível antes de remover temporários.",
    },
    "data-quality-guardian": {
        "title": "Guardião dos dados", "subtitle": "Profiling, schema, anomalias e plano de correção",
        "description": "Audita CSV, Parquet, JSON ou tabelas por profiling, anomalias e schema; calcula qualidade em seis dimensões e propõe remediações, com opção de checagem rápida.",
        "genres": ["Dados", "Qualidade"], "traits": ["Mensurável", "Investigativa", "Rastreável"],
        "requires": "Dataset acessível, schema esperado e baseline ou SLAs quando disponíveis",
        "example": "Audite a qualidade deste dataset com score e plano de remediação",
        "entry": "agents/data-profiler.md", "workflow": "workflows/full-data-quality-audit-workflow.yaml",
        "refs": [("Checagem rápida", "workflows/quick-data-check-workflow.yaml"), ("Contrato da auditoria", "tasks/full-data-quality-audit.md"), ("Cálculo do relatório", "tasks/generate-quality-report.md")],
        "when": "Use para uma auditoria completa de qualidade ou sanity check antes de usar dados. Diferencie profundidade quick/standard/deep e checagem rápida do pipeline completo.",
        "steps": [
            "Leia a capability escolhida em `squad.yaml` e o workflow correspondente. Data-profiler executa `tasks/profile-dataset.md`: tipos, distribuição, nulls e cardinalidade por coluna, com tamanho e cobertura informados.",
            "Na auditoria completa, anomaly-detector examina outliers, valores impossíveis e drift contra baseline; schema-validator verifica constraints, integridade e breaking changes. Na checagem rápida, siga profiler → schema-validator → reporter sem acrescentar a auditoria completa.",
            "Data-quality-reporter consolida evidências e score das seis dimensões: completude, acurácia, consistência, tempestividade, unicidade e validade. Explique dimensões não mensuráveis e violações de SLA em vez de preencher números fictícios.",
            "No fluxo completo, remediation-suggester produz `tasks/suggest-remediation.md`, priorizando impacto e esforço. Entregue scripts de limpeza como propostas; a capability original não executa a limpeza no dataset."
        ],
        "pitfalls": "Sem baseline não se comprova drift; outlier não implica erro. Uma amostra não equivale a profiling de 100% dos registros. Preserve o dataset e não chame sugestão de correção aplicada.",
        "verify": "Cobertura de colunas/linhas declarada, achados reproduzíveis e severidade explícita; relatório de schema e score sustentado por evidências; remediação priorizada somente quando o fluxo completo foi solicitado.",
    },
    "flywheel-core": {
        "title": "Execução em ciclos", "subtitle": "Plano, tarefas atômicas, coordenação e revisão",
        "description": "Estrutura trabalho de agentes no ciclo Flywheel: plano, beads com dependências, priorização, coordenação da execução e hardening com gates de qualidade.",
        "genres": ["Agentes de IA", "Engenharia"], "traits": ["Coordenada", "Incremental", "Revisada"],
        "requires": "Projeto e objetivo; scripts BV/BR/UBS originais não incluídos no pacote",
        "example": "Organize a implementação desta funcionalidade em um ciclo Flywheel com beads",
        "entry": "agents/flywheel-architect.md", "workflow": "workflows/flywheel-execution-cycle.yaml",
        "refs": [("Hardening", "workflows/hardening-pipeline.yaml"), ("Gate L1/L2/L3", "checklists/hardening-quality-gate.md"), ("Template de plano", "templates/plan-space.template.md"), ("Template de bead", "templates/bead.template.md")],
        "when": "Use para coordenar implementação composta por tarefas dependentes ou revisar um ciclo existente. Receba escopo e critérios de aceite; use o fluxo de hardening quando apenas revisão for necessária.",
        "steps": [
            "Flywheel-architect aplica `tasks/generate-plan.md` e `tasks/decompose-beads.md` para criar `PLAN_SPACE.md` e `BEADS.md` com contratos e dependências, utilizando os templates originais.",
            "Bead-manager refina os beads e sincroniza contexto com `tasks/polish-beads.md` e `tasks/sync-context.md`. Não distribua tarefas cujas entradas ou critérios ainda estejam indefinidos.",
            "Swarm-coordinator lê as tasks de priorização, lock e status; atribua responsáveis e evite edição concorrente do mesmo artefato. `squad.yaml` declara bv.js, br.js e ubs.js, mas os scripts não estão presentes: use registro manual das dependências/locks quando suficiente e declare as verificações automatizadas indisponíveis.",
            "Hardening-specialist executa as revisões descritas no pipeline de hardening. O gate bloqueia L1 (sintaxe/estrutura) e L2 (lógica/regras); L3 é informativo. Não alegue revisão multi-modelo nem execução de UBS sem ferramentas e resultados reais."
        ],
        "pitfalls": "Não instale executáveis de nome parecido para substituir scripts ausentes. Recovery e loop_on_beads não autorizam repetição infinita: ao repetir a mesma falha sem nova evidência, registre o bloqueio do bead e prossiga com os independentes.",
        "verify": "Plano e beads com responsáveis, dependências e critérios; execução rastreável; gate L1/L2 atendido ou explicitamente pendente; limitações dos scripts ausentes e qualquer revisão sequencial identificadas no relatório.",
    },
    "genius-athena-strange": {
        "title": "Decisões sob incerteza", "subtitle": "Cisnes Negros, antifragilidade e limites de exposição",
        "description": "Aplica os frameworks de Taleb a sistemas e decisões: mapeia incerteza, projeta antifragilidade, examina Barbell e audita seis critérios de fragilidade.",
        "genres": ["Estratégia", "Risco"], "traits": ["Cética", "Antifrágil", "Prudente"],
        "requires": "Decisão ou sistema, exposições, limites e contexto das partes envolvidas",
        "example": "Avalie a fragilidade desta estratégia e proponha opções com downside limitado",
        "entry": "agents/hermes-orquestrador.md", "workflow": "workflows/taleb-pipeline.yaml",
        "refs": [("Seis critérios de fragilidade", "checklists/fragility-gate.md"), ("Modelo Barbell", "templates/barbell-template.md")],
        "when": "Use para avaliar fragilidade, exposição assimétrica e tomada de decisão com informação incompleta. Os cenários ilustram possibilidades; não são previsões de eventos extremos.",
        "steps": [
            "Hermes delimita o sistema; Cygnus segue `tasks/mapear-cisnes-negros.md` para classificar variáveis, vieses, exposições côncavas/convexas e possíveis choques. Registre limites da evidência.",
            "Hydra aplica `tasks/projetar-antifragilidade.md`: tríade frágil/robusto/antifrágil, Via Negativa, opcionalidade e pontos únicos de falha. Compare remoções e adições antes de recomendar complexidade.",
            "Seneca aplica `tasks/aplicar-barbell.md`, descrevendo polos, exposições, limiar de ruína e pré-mortem. Os percentuais do template são parâmetros do framework, não uma alocação adequada automaticamente ao usuário.",
            "Medusa executa `tasks/auditar-fragilidade.md` contra todos os seis critérios; falha exige remediação antes de PASSED. Hermes sintetiza mapa, blueprint, estratégia, auditoria e plano de ação com `tasks/sintetizar-relatorio.md`."
        ],
        "pitfalls": "Não prometa risco zero, previsão de Cisnes Negros ou segurança de uma alocação com base apenas no checklist. Se a evidência não sustenta downside limitado ou ausência de SPOF, mantenha o critério pendente/reprovado.",
        "verify": "Classificações e exposições explícitas, pelo menos três cenários de choque no fluxo completo, Via Negativa e opcionalidades documentadas; os seis critérios têm evidência e status, sem aprovar itens não comprovados.",
    },
    "incident-response-squad": {
        "title": "Do alerta ao post-mortem", "subtitle": "Diagnóstico de incidente e plano de resposta para o operador",
        "description": "Analisa logs de incidentes, correlaciona causa raiz e impacto, prepara runbook, mensagens de status e post-mortem; oferece triagem rápida sobre dados fornecidos.",
        "genres": ["DevOps", "Confiabilidade"], "traits": ["Rastreável", "Objetiva", "Sem culpabilização"],
        "requires": "Alerta, severidade SEV1–SEV4 e logs fornecidos pelo operador",
        "example": "Faça a triagem deste incidente com os logs e prepare o plano de resposta",
        "entry": "agents/log-analyzer.md", "workflow": "workflows/full-incident-response-workflow.yaml",
        "refs": [("Triagem rápida", "workflows/rapid-triage-workflow.yaml"), ("Contrato de resposta", "tasks/full-incident-response.md"), ("Runbook", "tasks/execute-runbook.md")],
        "when": "Use em incidentes DevOps/SRE para apoio à decisão a partir de logs já fornecidos. Escolha triagem (logs, hipótese e status inicial) ou pacote completo (inclui remediação especificada e post-mortem).",
        "steps": [
            "Leia a capability em `squad.yaml`, que delimita o modo decision-support, e o workflow selecionado. Log-analyzer segue `tasks/analyze-incident-logs.md`; registre fontes, horários, severidade e lacunas.",
            "Root-cause-correlator executa `tasks/correlate-root-cause.md`: correlacione sinais, proponha hipóteses, blast radius e confiança justificada. Falta de evidência não permite declarar causa confirmada.",
            "Na resposta completa, runbook-executor prepara uma spec com pré-condições, ações, validação pré/pós e rollback. `execution-log.md` é plano para o operador enquanto não houver execução real. Status-page-updater prepara drafts adequados à severidade; execução e publicação ficam com o operador no contrato original.",
            "Postmortem-writer consolida timeline, fatores contribuintes, impacto e action items em `tasks/write-postmortem.md`. Se a remediação ainda não foi executada, o documento permanece parcial e não declare o incidente resolvido."
        ],
        "pitfalls": "O workflow antigo descreve runbook executado e stakeholders notificados; a capability atual especifica planejamento e drafts. Preserve esse limite: instruções arquivadas não dão autorização para alterar produção ou enviar mensagens.",
        "verify": "Logs e timeline citados, hipótese e confiança separadas de confirmação, impacto descrito; runbook verificável e drafts claramente identificados; post-mortem reflete somente ações comprovadas e donos/prazos conhecidos.",
    },
    "instagram-caption-writer": {
        "title": "Legendas com intenção", "subtitle": "Ganchos, variações e planejamento para Instagram",
        "description": "Escreve ou diagnostica legendas de Instagram, cria ganchos e pilares, adapta formatos e planeja cinco posts semanais com variações, CTAs e sugestões de hashtags.",
        "genres": ["Instagram", "Copywriting"], "traits": ["Persuasiva", "Adaptável", "Planejada"],
        "requires": "Tema, nicho, formato, objetivo e tom; produto/oferta quando houver venda",
        "example": "Crie uma semana de conteúdo de Instagram para este nicho e objetivo",
        "entry": "agents/instagram-caption-chief.md", "workflow": "workflows/content-week-in-one-shot.md",
        "refs": [("Legenda avulsa", "tasks/write-caption.md"), ("Análise de post viral", "workflows/viral-post-anatomy.md"), ("Padrão de saída", "templates/caption-output.md"), ("Regras da plataforma", "config/platform-rules.md")],
        "when": "Use para legendas, hooks, diagnóstico, pilares, reaproveitamento ou planejamento semanal de Instagram. O chief roteia o pedido; não force o workflow semanal em uma legenda avulsa.",
        "steps": [
            "Leia o chief e selecione a task/fluxo. Reaproveite tema, nicho, formato, objetivo e tom já informados; resolva campos obrigatórios ausentes antes da criação.",
            "Para legenda avulsa: caption-strategist define ângulo, caption-writer gera três variações e hashtag-researcher organiza sugestões. Use hook-generator, caption-ab-tester ou caption-repurposer somente conforme o pedido.",
            "Para a semana: strategist distribui cinco ângulos e formatos e apresenta o mapa ao usuário. Preserve a aprovação do mapa antes de produzir; após o gate, gere duas variações por dia (dez ao todo), seguindo a exceção explícita desse workflow.",
            "Consolide CTA, sugestões de hashtags e horário no template. As quantidades e regras do original são uma referência datada: confira limites atuais da plataforma quando necessário e diferencie sugestão de dado de competitividade verificado."
        ],
        "pitfalls": "A regra geral de três variações não vale para o modo semanal de duas. Não invente depoimentos, resultados, tendência, competitividade ou horário ideal sem evidência. Entregar legenda pronta não equivale a publicar.",
        "verify": "Formato e tom adequados ao briefing; três variações na task avulsa ou cinco posts com duas variações após aprovação do mapa; CTAs coerentes e hashtags revisadas quanto à relevância e regras vigentes.",
    },
    "landing-funnel": {
        "title": "Funil de conversão completo", "subtitle": "Landing page, integrações, analytics e experimentos",
        "description": "Coordena criação e otimização de landing pages: discovery, pesquisa, copy, design, prova social, build, integrações, analytics, QA e testes A/B com gates explícitos.",
        "genres": ["Conversão", "Web"], "traits": ["Integrada", "Orientada a dados", "Criteriosa"],
        "requires": "Brief do produto, evidências, projeto web e acessos autorizados às integrações usadas",
        "example": "Use Landing Funnel para construir esta landing page e verificar o funil de leads",
        "entry": "agents/ce-strategist.md", "workflow": "workflows/ce-full-pipeline.yaml",
        "refs": [("Discovery", "workflows/ce-discovery-flow.yaml"), ("QA", "workflows/ce-qa-gate.yaml"), ("Preparação do lançamento", "workflows/ce-launch-prep.yaml"), ("Experimento A/B", "workflows/ce-ab-design.yaml")],
        "when": "Use para construir uma landing page ou executar uma fase específica de otimização do funil. Delimite fases e integrações realmente pedidas; o pacote também oferece sub-workflows independentes.",
        "steps": [
            "Ce-strategist aplica discovery e obtém brief aprovado com proposta de valor e escopo. O pipeline completo requer 12 campos; menos de oito bloqueia. Ce-researcher produz intelligence com cinco concorrentes, três personas, dez ganchos e evidência de tráfego; registre indisponibilidades, sem fabricar a pesquisa.",
            "Copywriter, design-architect e social-proof produzem artefatos antes do merge gate que libera image-creator. Leia tasks correspondentes e `workflows/ce-copy-design-parallel.yaml`; use apenas prova social comprovada e assets adequados ao produto.",
            "Frontend, backend e analytics seguem `workflows/ce-build-parallel.yaml`. Após o integration gate, ce-integrator valida o percurso lead → CRM → email → confirmação no ambiente autorizado. Use versões e ferramentas do projeto; a stack listada no original não autoriza migração de um projeto existente.",
            "Ce-reviewer aplica QA e launch-prep: score geral >=75, nenhuma dimensão <60, sem falhas críticas de acessibilidade/formulário, PageSpeed >=90 mobile/desktop e eventos verificados. Registre cada evidência; gates não medidos permanecem pendentes. Publicação e testes que enviam dados/mensagens dependem do escopo autorizado.",
            "Só realize pós-lançamento e A/B se pedidos e com dados disponíveis: fluxo original exige 500 sessões para insights e, para declarar vencedor, pelo menos sete dias, 100 conversões por variante e p<=0,05. Documente também desenho e limitações estatísticas; ausência de dados não permite simular resultado."
        ],
        "pitfalls": "O original usa nomes de modos e descreve webhooks em produção; isso não concede novos acessos nem dispensa gates. Não publique depoimentos fictícios, não ative envios por pressuposição e não declare experimento vencedor apenas por diferença numérica.",
        "verify": "Cada fase contratada tem entradas, saídas e gates com evidência; merge e integration gates completos antes dos próximos passos; fluxo de conversão comprovado no ambiente autorizado e bloqueios de lançamento/experimento reportados com clareza.",
    },
    "linkedin": {
        "title": "Presença no LinkedIn", "subtitle": "Tendências, voz autoral, posts e carrosséis",
        "description": "Planeja conteúdo de LinkedIn, analisa perfil e tendências e cria posts, carrosséis ou roteiros com voz autoral; inclui ciclo semanal voltado a CyberSec e IA.",
        "genres": ["LinkedIn", "Marca Pessoal"], "traits": ["Autoral", "Editorial", "Consistente"],
        "requires": "Público, objetivo, voz e contexto do autor; fontes atuais para tendências",
        "example": "Planeje meu conteúdo semanal no LinkedIn sobre segurança e automação com IA",
        "entry": "agents/linkedin-chief.md", "workflow": "workflows/weekly-content-cycle.yaml",
        "refs": [("Estilo de referência original", "data/writing-style.md"), ("Análise de perfil", "tasks/analyze-profile.md"), ("Template de post", "templates/post-template.md"), ("Template de carrossel", "templates/carousel-template.md")],
        "when": "Use para presença autoral no LinkedIn: perfil, tópicos, posts, carrosséis, roteiro ou calendário semanal. O domínio padrão é segurança ofensiva e automação com IA; adapte ao briefing real.",
        "steps": [
            "Leia linkedin-chief e a task pertinente. Identifique quem é o autor e seus pilares. `data/writing-style.md` e `outputs/` registram o autor de origem; use como referência de estrutura, sem atribuir suas experiências ao usuário.",
            "No ciclo semanal, trend-scout pesquisa a última semana e prioriza fontes. Se pesquisa atual não estiver disponível, use explicitamente backlog evergreen, conforme o fallback do workflow.",
            "Linkedin-chief escolhe tema/ângulo/formato; ghostwriter redige post, carousel-designer estrutura slides ou scriptwriter segue `tasks/generate-script.md`. Leia apenas agentes, task e template necessários ao formato escolhido.",
            "Linkedin-chief revisa hook inicial, voz, ausência de clichês e CTA natural. Entregue conteúdo revisado e plano com data/horário como sugestão; a revisão editorial do squad não significa aprovação para publicar na conta."
        ],
        "pitfalls": "O original menciona Sid e exemplos de projetos pessoais: não copie essa identidade nem invente vivências. Tendência exige fonte atual; uma sugestão de calendário não é agendamento realizado.",
        "verify": "Conteúdo coerente com pilares e voz do usuário, fatos com origem, hook nas primeiras linhas e CTA natural; formato e plano semanal completos quando pedidos, prontos para revisão final do autor.",
    },
    "skeptic-protocol": {
        "title": "Ceticismo que testa", "subtitle": "Acusações de falha, testes, implementação e revisão adversarial",
        "description": "Aplica o SKEPTIC Protocol à engenharia de software: antecipa falhas, escreve testes que falham, implementa a solução, faz revisão adversarial e entrega um veredito.",
        "genres": ["Engenharia", "Qualidade"], "traits": ["Cética", "Testável", "Preventiva"],
        "requires": "Requisito ou código, ambiente de testes e escopo autorizado de alteração",
        "example": "Aplique o SKEPTIC Protocol a esta implementação e verifique os casos extremos",
        "entry": "agents/skeptic-orchestrator.md", "workflow": "workflows/skeptic-pipeline-execution.yaml",
        "refs": [("Loop de revisão", "workflows/red-team-feedback-loop.yaml"), ("Acusações", "tasks/generate-accusations.md"), ("Veredito", "tasks/generate-verdict-report.md")],
        "when": "Use para implementar ou revisar software com prevenção explícita de falhas e testes verificáveis. Limite a revisão adversarial ao sistema e às ações autorizadas pelo usuário.",
        "steps": [
            "Skeptic-orchestrator delimita requisito e escopo; failure-predictor aplica `tasks/generate-accusations.md` para produzir `accusationsList` com falhas plausíveis e condições que as revelam.",
            "Test-engineer executa `tasks/write-failing-tests.md`. O gate exige que a suíte compile e falhe pelo comportamento esperado antes de liberar implementação; erro de setup não conta como teste vermelho válido.",
            "Solution-implementer segue `tasks/implement-trial-code.md` até os testes passarem. Red-teamer aplica `tasks/execute-appeal.md` a edge cases e evidências, mantendo registros da revisão separados da implementação.",
            "Se appealResult for falso, siga o feedback loop: falhas extremas retornam à acusação/teste; falhas menores geram correção e novos testes. Encerre quando não restar falha relevante conhecida ou reporte um bloqueio verificável, sem repetição ilimitada. Gere `SKEPTIC_REPORT.md` apenas com resultados efetivamente observados."
        ],
        "pitfalls": "Testes que só repetem a implementação não provam o requisito. Não chame revisão sequencial de auditoria independente, nem suíte não executada de aprovada. Ausência de novo edge case não é prova de ausência de defeitos.",
        "verify": "Acusações rastreadas a testes; evidência do ciclo vermelho/verde; retorno adversarial tratado; veredito inclui comandos, resultados, riscos restantes e status real de appealResult.",
    },
    "token-optimizer": {
        "title": "Menos tokens, mesma função", "subtitle": "Auditoria e otimização de squads por impacto e custo",
        "description": "Audita squads AIOS por inventário, anti-patterns e dependências; prioriza otimizações de tokens e qualidade, aplica mudanças quando pedidas e compara antes/depois.",
        "genres": ["Agentes de IA", "Eficiência"], "traits": ["Mensurável", "Conservadora", "Priorizada"],
        "requires": "Pasta de squad AIOS; guia TOKEN-OPTIMIZATION-GUIDE.md não incluído no pacote",
        "example": "Audite este squad e proponha otimizações de tokens sem perder seus contratos",
        "entry": "agents/squad-scanner.md", "workflow": "workflows/optimization-pipeline.yaml",
        "refs": [("Somente auditoria", "workflows/audit-only.yaml"), ("Inventário", "tasks/scan-squad.md"), ("Plano de otimização", "tasks/plan-optimization.md"), ("Auditoria de resultado", "tasks/audit-quality.md")],
        "when": "Use para diagnosticar custo de contexto de um squad AIOS existente ou executar otimizações solicitadas. Para auditoria, use audit-only e mantenha os arquivos do squad intactos.",
        "steps": [
            "Leia squad-scanner e `tasks/scan-squad.md`; catalogue cada arquivo uma vez em `squad-inventory.json`, com agentes, tasks, workflows, contratos e dependências. Registre método de estimativa de tokens.",
            "Anti-pattern-detector executa `tasks/detect-anti-patterns.md`, classificando achados por evidência e severidade. O original depende de `TOKEN-OPTIMIZATION-GUIDE.md`, ausente desta cópia: solicite essa referência apenas se indispensável; de outro modo limite o diagnóstico às regras presentes e sinalize cobertura parcial.",
            "Em audit-only, quality-auditor entrega findings e economias projetadas. No fluxo completo, optimization-planner cria plano priorizado por ROI; optimization-executor aplica `tasks/execute-optimization.md` somente no alvo solicitado, preservando contratos e material necessário.",
            "Quality-auditor compara before/after, valida referências e funcionalidade preservada. Diferencie tokens medidos de estimados e economia projetada de obtida; entregue `optimization-report.md` com mudanças, evidências e limites."
        ],
        "pitfalls": "Não invente o conteúdo do guia ausente, porcentagens de economia ou ganhos de qualidade. Redução de texto que quebra dependências ou remove gates não é otimização bem-sucedida; não execute o pipeline de escrita para um pedido de auditoria.",
        "verify": "Inventário e grafo completos para o escopo lido; achados apontam arquivos concretos; relatório separa projeções de resultados, mostra antes/depois quando houve alterações e comprova preservação dos contratos disponíveis.",
    },
    "win-proposal-deal": {
        "title": "Proposta em três opções", "subtitle": "Prospect, escopo, preço e tratamento de objeções",
        "description": "Monta propostas comerciais com análise do prospect, três escopos, precificação e dez seções de proposta; inclui playbook de objeções e fluxo de revisão.",
        "genres": ["Vendas", "Propostas"], "traits": ["Consultiva", "Estruturada", "Persuasiva"],
        "requires": "Contexto do prospect, oferta, capacidade de entrega, custos e condições comerciais",
        "example": "Monte uma proposta comercial com três opções de escopo para este prospect",
        "entry": "agents/prospect-analyzer.md", "workflow": "workflows/proposal-generation-pipeline.yaml",
        "refs": [("Revisão de proposta", "workflows/proposal-revision-flow.yaml"), ("Precificação", "tasks/calculate-pricing.md"), ("Composição e gates", "tasks/compose-proposal.md")],
        "when": "Use para estruturar o conteúdo e as condições de uma proposta comercial ou revisar uma existente. A entrega padrão é Markdown; necessidade de HTML/PDF deve ser tratada como formato adicional do pedido.",
        "steps": [
            "Prospect-analyzer aplica `tasks/analyze-prospect.md`: perfil, dores, objetivos e objeções sustentados pelo briefing e fontes disponíveis. Mantenha suposições explícitas.",
            "Scope-architect segue `tasks/design-scope.md` e produz três versões de escopo com entregáveis, cronograma, marcos, dependências e critérios de aceite. Não inicie preço antes de definir o que cada versão entrega.",
            "Pricing-strategist lê sua definição e `tasks/calculate-pricing.md` para custos, margens e descontos condicionais. Qualquer win-rate preditivo exige base e método; sem histórico, apresente cenário heurístico identificado, sem inventar probabilidade ou intervalo de confiança estatístico.",
            "Proposal-composer recebe perfil, três escopos, timeline e estratégia de preço. Leia `agents/proposal-composer.md` para as dez seções e `tasks/compose-proposal.md` para o gate. Produza `proposal-final.md` e `objection-playbook.md`; win-rate é análise interna, não texto para o prospect. Use o fluxo de revisão se houver feedback."
        ],
        "pitfalls": "Não prometa fechamento, ROI ou resultados do cliente sem evidência. Validade, desconto e condições precisam corresponder ao negócio; não envie a proposta ao prospect só porque o pacote a chama de pronta para envio.",
        "verify": "Três escopos comparáveis, preço reconciliado com custos/condições, dez seções completas, recomendação justificada, validade e próximo passo concretos; objeções tratadas e estimativas internas distinguidas de fatos.",
    },
}


def digest(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def as_bytes(content: str) -> bytes:
    return content.encode("utf-8")


def source_provenance(slug: str) -> str:
    if slug in {"data-quality-guardian", "incident-response-squad"}:
        return "https://github.com/gutomec/nirvana-squads-free — commit 6134bf9 (2026-06-25), cópia em 2026-09-16."
    if slug in {"apex-context-supreme", "genius-athena-strange"}:
        return "https://github.com/marciobisognin/Squads-Genius — commit 34f431d (2026-07-20), cópia em 2026-09-16."
    return f"Registro https://squads.sh, slug `{slug}`, cópia em 2026-09-16; proveniência detalhada no README arquivado."


def build_skill(source_root: Path, slug: str, spec: dict) -> dict[str, bytes]:
    source = source_root / slug
    if not source.is_dir() or source.is_symlink():
        raise ValueError(f"Origem ausente ou link simbólico: {source}")
    files: dict[str, bytes] = {}
    inventory = []
    for path in sorted(source.rglob("*")):
        if path.is_symlink():
            raise ValueError(f"Link simbólico não permitido: {path}")
        if path.is_file():
            relative = path.relative_to(source).as_posix()
            data = path.read_bytes()
            files[f"references/squad/{relative}"] = data
            inventory.append({"path": relative, "bytes": len(data), "sha256": digest(data)})
    squad = yaml.safe_load(files["references/squad/squad.yaml"].decode("utf-8-sig"))
    if squad["name"] != slug:
        raise ValueError(f"Slug incompatível: {slug} != {squad['name']}")
    components = squad.get("components", {})
    author = squad.get("author") or "Não informado no pacote original"
    license_id = squad.get("license") or "LicenseRef-Unspecified"
    expected_license = {"landing-funnel": "Commercial", "instagram-caption-writer": "LicenseRef-Unspecified"}.get(slug, "MIT")
    if license_id != expected_license:
        raise ValueError(f"Licença mudou em {slug}; revisar a adaptação antes de importar")
    if len(spec["description"]) > 200:
        raise ValueError(f"Descrição longa: {slug}")
    referenced = [("Manifesto original e contratos", "squad.yaml"), ("Ponto de entrada", spec["entry"]), ("Workflow principal", spec["workflow"])] + spec["refs"]
    for _, ref in referenced:
        if f"references/squad/{ref}" not in files:
            raise ValueError(f"Referência inexistente em {slug}: {ref}")
    # Validate all wrapper paths written in the domain-specific guidance.
    guidance = "\n".join(spec["steps"]) + spec["pitfalls"]
    for ref in re.findall(r"`((?:tasks|agents|workflows|templates|checklists|data)/[^`]+\.(?:md|yaml))`", guidance):
        if f"references/squad/{ref}" not in files:
            raise ValueError(f"Referência de procedimento inexistente em {slug}: {ref}")
    missing = []
    for kind in ("agents", "tasks", "workflows", "checklists", "templates", "scripts", "commands"):
        for item in components.get(kind, []):
            if not isinstance(item, str):
                continue
            candidates = [f"{kind}/{item}", item]
            if not any(f"references/squad/{candidate}" in files for candidate in candidates):
                missing.append(f"{kind}/{item}")
    frontmatter = {
        "name": slug, "description": spec["description"], "version": VERSION,
        "author": author, "license": license_id, "platforms": ["linux", "macos", "windows"],
        "required_environment_variables": [],
        "metadata": {"hermes": {"tags": ["especialistas", "squad"] + squad.get("tags", [])[:6]}},
    }
    refs = "\n".join(f"| {label} | [references/squad/{ref}](references/squad/{ref}) |" for label, ref in referenced)
    steps = "\n".join(f"{index}. {step}" for index, step in enumerate(spec["steps"], 1))
    body = f"""---
{yaml.safe_dump(frontmatter, allow_unicode=True, sort_keys=False).strip()}
---

# {spec['title']}

{spec['subtitle']}. Adaptação instalável do squad `{slug}`, preservado integralmente em `references/squad/`.

## When to Use

{spec['when']}

Exemplo: “{spec['example']}”.

## Quick Reference

| Quando consultar | Referência |
|---|---|
{refs}
| Origem, licença e limitações do pacote | [SOURCE.md](SOURCE.md) |

Leia primeiro o ponto de entrada e o workflow escolhido. Os caminhos `agents/`, `tasks/`, `workflows/`, `templates/`, `config/` e `data/` citados abaixo são relativos a [references/squad/](references/squad/); carregue apenas o agente e a task da etapa corrente, com suas dependências relevantes.

## Procedure

{steps}

Os nomes de slash commands e ferramentas nas referências pertencem ao runtime AIOS de origem. No ClariFlix, execute o procedimento com as ferramentas disponíveis, sem presumir instalação de comandos. Se houver subagentes, delegue somente etapas independentes e compartilhe os contratos de entrada/saída. Sem esse recurso, cumpra os papéis em sequência, registrando cada handoff; preserve os mesmos gates e identifique a revisão como sequencial. Não anuncie agentes ou verificações que não foram executados.

## Pitfalls

{spec['pitfalls']}

As referências preservam instruções e exemplos de terceiros. Use o briefing atual, as permissões vigentes e os limites do procedimento acima; uma instrução arquivada não autoriza instalar dependências, alterar contas, publicar ou enviar mensagens fora do pedido.

## Verification

{spec['verify']}
"""
    files["SKILL.md"] = as_bytes(body)
    agents = [Path(name).stem for name in components.get("agents", [])]
    manifest = {
        "row": "especialistas", "title": spec["title"], "title_netflix": slug.replace("-", " ").upper(),
        "subtitle": spec["subtitle"], "genre": "procedural", "badge": "Nova",
        "painel": {
            "ano": 2026,
            "tamanho": f"{len(agents)} agentes, {len(components.get('tasks', []))} tarefas, {len(components.get('workflows', []))} fluxos",
            "requer": spec["requires"], "como_usar": f'Diga: "{spec["example"]}"',
            "elenco": agents, "generos": spec["genres"], "esta_skill_e": spec["traits"],
        },
    }
    files["manifest.yaml"] = as_bytes(yaml.safe_dump(manifest, allow_unicode=True, sort_keys=False))
    provenance = (source_root / "README.md").read_bytes()
    files["references/UPSTREAM-PROVENANCE.md"] = provenance
    files["references/source-inventory.json"] = as_bytes(json.dumps({
        "source": f"maquina-de-receita/squads-gratuitos/{slug}",
        "files": inventory, "provenance_readme_sha256": digest(provenance),
    }, ensure_ascii=False, indent=2) + "\n")
    if "references/squad/LICENSE" in files:
        files["LICENSE"] = files["references/squad/LICENSE"]
        license_note = "O arquivo LICENSE original foi preservado byte a byte na raiz e na cópia do squad."
    else:
        license_note = f"O squad declara `{license_id}` em seu manifesto original." if license_id != "LicenseRef-Unspecified" else "O manifesto original não informa licença nem autor; LicenseRef-Unspecified registra essa ausência, sem conceder permissões."
        files["LICENSE"] = as_bytes(f"# Declaração de licença do pacote original\n\n{license_note}\n\nAutor declarado: {author}.\n\nEsta nota registra a declaração do pacote e não substitui nem amplia os termos do autor. Consulte references/squad/squad.yaml e SOURCE.md. A licença MIT da raiz do repositório ClariFlix não relicencia este material.\n")
    caveats = []
    if missing:
        caveats.append("Componentes declarados, mas ausentes na cópia original: " + ", ".join(f"`{path}`" for path in missing) + ".")
    if slug == "token-optimizer":
        caveats.append("`TOKEN-OPTIMIZATION-GUIDE.md`, citado por agentes/tasks, não acompanha o original; não há conteúdo inventado para substituí-lo.")
    if slug == "linkedin":
        caveats.append("`outputs/` e `data/writing-style.md` são exemplos do autor de origem e não fatos sobre quem instalar a skill.")
    if slug == "incident-response-squad":
        caveats.append("O YAML de workflow usa linguagem de execução/publicação, enquanto a capability atual delimita decision-support. A adaptação conserva o limite de planejamento e drafts da capability.")
    caveats_text = "\n".join(f"- {item}" for item in caveats) or "- Os arquivos originais foram preservados sem alteração; comandos e dependências AIOS não são instalados nem executados pelo ClariFlix."
    files["SOURCE.md"] = as_bytes(f"""# Origem e adaptação

<!-- Managed by {MANAGED_BY} -->

- Origem local: `maquina-de-receita/squads-gratuitos/{slug}`.
- Origem anterior, conforme o README do acervo: {source_provenance(slug)}
- Autor declarado no pacote: {author}.
- Versão original: {squad.get('version', 'não informada')}; adaptação ClariFlix: {VERSION}.
- Licença original: `{license_id}`. {license_note}
- Em 2026-09-18, o mantenedor informou possuir autorização dos autores para publicar todos os squads no ClariFlix. Essa autorização informada não é uma mudança de licença nem concede automaticamente novos direitos aos instaladores.

A adaptação acrescenta `SKILL.md` e `manifest.yaml`, roteamento por domínio, execução sequencial quando não há subagentes e limites para evidências, ferramentas e ações externas. O conteúdo original completo está em [references/squad/](references/squad/), com hashes SHA-256 em [references/source-inventory.json](references/source-inventory.json).

O [README original de proveniência](references/UPSTREAM-PROVENANCE.md) também foi preservado. Ele contém uma inconsistência de contagem: diz “doze declaram MIT”, mas a lista tem onze MIT, um Commercial e um sem licença. Esta adaptação usa os metadados de cada `squad.yaml` e não corrige o arquivo histórico.

## Limitações conhecidas

{caveats_text}

## Reprodução

Na raiz do repositório, execute `python scripts/import_free_squads.py --source-root <pasta-maquina-de-receita>`. Para verificar sem alterar arquivos, acrescente `--check`. O importador recusa destinos que não gerencia e valida referências diretas e integridade da cópia; ele não executa squads nem verifica suas alegações de desempenho.
""")
    return files


def safe_file(root: Path, relative: str) -> Path:
    path = root / relative
    if path.is_symlink() or not path.resolve().is_relative_to(root.resolve()):
        raise ValueError(f"Destino fora da pasta gerenciada: {path}")
    return path


def preflight(destination: Path, files: dict[str, bytes]) -> set[str]:
    if destination.is_symlink():
        raise ValueError(f"Destino é link simbólico: {destination}")
    marker_path = destination / ".clariflix-import.json"
    prior: set[str] = set()
    if destination.exists():
        if not marker_path.is_file():
            raise ValueError(f"Recusando sobrescrever destino não gerenciado: {destination}")
        previous = json.loads(marker_path.read_text(encoding="utf-8"))
        if previous.get("managed_by") != MANAGED_BY:
            raise ValueError(f"Destino pertence a outro importador: {destination}")
        prior = set(previous["files"])
        for relative in prior:
            safe_file(destination, relative)
        actual = {path.relative_to(destination).as_posix() for path in destination.rglob("*") if path.is_file()}
        unknown = actual - prior - {".clariflix-import.json"}
        if unknown:
            raise ValueError(f"Arquivos não gerenciados em {destination}: {sorted(unknown)}")
    for relative in files:
        safe_file(destination, relative)
    return prior


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", type=Path, required=True)
    parser.add_argument("--output-root", type=Path, default=Path(__file__).resolve().parents[1] / "skills")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    source_root = args.source_root.resolve()
    if (source_root / "squads-gratuitos").is_dir():
        source_root = source_root / "squads-gratuitos"
    output_root = args.output_root.resolve()
    plans = []
    # All validation happens before the first filesystem mutation.
    for slug, spec in SPECS.items():
        files = build_skill(source_root, slug, spec)
        destination = output_root / slug
        prior = preflight(destination, files)
        marker = {"managed_by": MANAGED_BY, "version": VERSION, "files": {name: digest(content) for name, content in sorted(files.items())}}
        files[".clariflix-import.json"] = as_bytes(json.dumps(marker, ensure_ascii=False, indent=2) + "\n")
        plans.append((destination, files, prior))
    differences = []
    for destination, files, prior in plans:
        for relative, content in files.items():
            path = safe_file(destination, relative)
            if args.check:
                if not path.is_file() or path.read_bytes() != content:
                    differences.append(f"{destination.name}/{relative}")
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                if not path.exists() or path.read_bytes() != content:
                    path.write_bytes(content)
        for relative in prior - set(files):
            path = safe_file(destination, relative)
            if args.check:
                differences.append(f"arquivo obsoleto: {destination.name}/{relative}")
            elif path.is_file():
                path.unlink()
    if differences:
        print("Divergências de reprodução:\n" + "\n".join(differences), file=sys.stderr)
        return 1
    if not args.check:
        for destination, files, _ in plans:
            for relative, content in files.items():
                if safe_file(destination, relative).read_bytes() != content:
                    raise ValueError(f"Falha de integridade após escrita: {destination}/{relative}")
    count = sum(sum(name.startswith("references/squad/") for name in files) for _, files, _ in plans)
    print(f"{len(plans)} skills {'verificadas' if args.check else 'importadas'}; {count} arquivos originais preservados e verificados.")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (ValueError, OSError, KeyError, yaml.YAMLError) as error:
        print(f"Erro: {error}", file=sys.stderr)
        raise SystemExit(1)
